-- CreateEnum
CREATE TYPE "B2BStage" AS ENUM (
  'SALES_RECEPTION',
  'SALES_DIAGNOSIS',
  'ONBOARDING_ASSISTED',
  'ONBOARDING_COMPLETED',
  'WAITING',
  'HANDOFF_HUMAN'
);

-- AlterTable
ALTER TABLE "conversation"
ADD COLUMN "stage_b2b" "B2BStage" NOT NULL DEFAULT 'SALES_RECEPTION';


